apiVersion: apps/v1
kind: Deployment
metadata:
  name: grwthy-api
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: api
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grwthy-api
spec:
  rules:
    - host: dev.grwthy.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: grwthy-api
                port:
                  number: 3001
