apiVersion: v1
kind: ServiceAccount
metadata:
  name: grwthy-api
  labels:
    app: grwthy-api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grwthy-api
  labels:
    app: grwthy-api
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grwthy-api
  labels:
    app: grwthy-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grwthy-api
subjects:
  - kind: ServiceAccount
    name: grwthy-api
