apiVersion: v1
kind: ConfigMap
metadata:
  name: grwthy-api-config
data:
  APP_PORT: "3000"
  NODE_ENV: production
  WMA_BASE_URL: http://grwthy-whatsapp
  APP_CORS_ORIGIN: "*"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grwthy-web-config
data:
  PORT: "3000"
  NEXT_PUBLIC_API_URL: http://grwthy-api
  NEXT_PUBLIC_CNPJ: "55.936.992/0001-55"
  API_URL: http://grwthy-api
  GATEWAY_INTERNAL_URL: http://grwthy-api
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grwthy-whatsapp-config
data:
  PORT: "3000"
  NODE_ENV: production
  APP_CORS_ORIGIN: "*"
  META_API_URL: https://graph.facebook.com
  META_API_VERSION: v21.0
  REDIS_PREFIX: "wma:"
  REDIS_TTL: "300"
  LOG_LEVEL: info
  S3_ENDPOINT: minio
  S3_PORT: "9000"
  S3_USE_SSL: "false"
  S3_BUCKET_NAME: whatsapp-media
  S3_REGION: us-east-1
