apiVersion: apps/v1
kind: Deployment
metadata:
  name: grwthy-web
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: web
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grwthy-web
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: grwthy-prod-redirect-https@kubernetescrd
spec:
  tls:
    - hosts:
        - grwthy.com
      secretName: grwthy-web-tls
  rules:
    - host: grwthy.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grwthy-web
                port:
                  number: 3000
