apiVersion: apps/v1
kind: Deployment
metadata:
  name: grwthy-web
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: web
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grwthy-web
spec:
  routes:
    - match: Host(`grwthy.com`)
      kind: Rule
      services:
        - name: grwthy-web
          port: 3000
